{% set name = "roman-numerals" %}
{% set version = "3.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace("-", "_") }}-{{ version }}.tar.gz
  sha256: 384e36fc1e8d4bd361bdb3672841faae7a345b3f708aae9895d074c878332551

build:
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - flit-core >=3.7,<4
    - pip
  run:
    - python

test:
  source_files:
    - tests
  imports:
    - roman_numerals
  commands:
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pip check
    - pytest -vv .
  requires:
    - python
    - pip
    - pytest >=8

about:
  home: https://github.com/AA-Turner/roman-numerals
  summary: Manipulate well-formed Roman numerals
  description: |
    This project provides utilities manipulating well-formed Roman 
    numerals, in various programming languages. Currently, 
    there are implementations in Python and Rust.
  license: 0BSD OR CC0-1.0
  license_file: LICENCE.rst

extra:
  recipe-maintainers:
    - ocefpaf
